# Generated by Django 5.0.4 on 2024-05-26 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='FAQsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faq_question_uz', models.CharField(max_length=255)),
                ('faq_question_en', models.CharField(max_length=255)),
                ('faq_answer_uz', models.TextField()),
                ('faq_answer_en', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='PublicationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pub_name_uz', models.CharField(max_length=50)),
                ('pub_name_en', models.CharField(max_length=50)),
                ('pub_name_ru', models.CharField(max_length=50)),
                ('pub_annotation_uz', models.TextField()),
                ('pub_annotation_en', models.TextField()),
                ('pub_annotation_ru', models.TextField()),
                ('pub_image', models.ImageField(upload_to='static/pub_image/')),
                ('pub_file_uz', models.FileField(upload_to='static/pub_file/')),
                ('pub_file_en', models.FileField(null=True, upload_to='static/pub_file/')),
                ('pub_file_ru', models.FileField(null=True, upload_to='static/pub_file/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='ReferencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_name', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='PapersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper_title_uz', models.CharField(max_length=50)),
                ('paper_title_en', models.CharField(max_length=50)),
                ('paper_annotation_uz', models.CharField(max_length=500)),
                ('paper_annotation_en', models.CharField(max_length=500)),
                ('views_count', models.IntegerField(default=0)),
                ('keyword', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper_pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_publications.publicationsmodel')),
                ('paper_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_publications.referencesmodel')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
        migrations.CreateModel(
            name='RequirementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('req_name_uz', models.CharField(max_length=255)),
                ('req_name_en', models.CharField(max_length=255)),
                ('req_description_uz', models.TextField()),
                ('req_description_en', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requirements',
            },
        ),
        migrations.CreateModel(
            name='ReviewersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=50)),
                ('reviewer_position_uz', models.CharField(max_length=50)),
                ('reviewer_position_en', models.CharField(max_length=50)),
                ('reviewer_position_ru', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviewers',
            },
        ),
        migrations.CreateModel(
            name='FeedbacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_file', models.FileField(upload_to='static/feedback/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('feedback_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_publications.papersmodel')),
                ('feedback_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_publications.reviewersmodel')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='SpheresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sphere_name_uz', models.CharField(max_length=50)),
                ('sphere_name_en', models.CharField(max_length=50)),
                ('sphere_name_ru', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spheres',
            },
        ),
        migrations.AddField(
            model_name='reviewersmodel',
            name='reviewer_sphere',
            field=models.ManyToManyField(to='app_publications.spheresmodel'),
        ),
        migrations.AddField(
            model_name='publicationsmodel',
            name='pub_sphere',
            field=models.ManyToManyField(to='app_publications.spheresmodel'),
        ),
        migrations.AddField(
            model_name='papersmodel',
            name='paper_sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_publications.spheresmodel'),
        ),
    ]
