# Generated by Django 5.0.4 on 2024-05-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsmodel',
            name='pub_file_uz',
            field=models.FileField(null=True, upload_to='static/pub_file/'),
        ),
    ]
