# Generated by Django 5.0.4 on 2024-05-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_publications', '0003_remove_publicationsmodel_pub_file_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationFilesModel',
        ),
    ]
