# Generated by Django 5.0.4 on 2024-05-27 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publications', '0004_delete_publicationfilesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersmodel',
            name='paper_annotation_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papersmodel',
            name='paper_title_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
